### ISSUE TITLE
ImportError: cannot import name 'mmr_auxe' from partially initialized module 'niftypet.nipet' 

### ISSUE THREAD

**Issue by Melissa1909** [NiftyPET/NiftyPET#19]
Dear developers, 
I have installed niftypet inside a docker container using the attached Dockerfile. However, if I start it and enter the Python3 venv (/venv/bin/python3) and import nipet from niftypet as given in the example scripts (from niftypet import nipet), I get the following error:

```
>>> from niftypet import nipet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/NIPET/niftypet/nipet/__init__.py", line 45, in <module>
    from . import img, lm, mmr_auxe, mmraux, mmrnorm, prj
  File "/venv/NIPET/niftypet/nipet/img/__init__.py", line 4, in <module>
    from . import auximg, mmrimg
  File "/venv/NIPET/niftypet/nipet/img/mmrimg.py", line 16, in <module>
[Dockerfile.txt](https://github.com/NiftyPET/NiftyPET/files/12313850/Dockerfile.txt)

    from .. import mmraux
  File "/venv/NIPET/niftypet/nipet/mmraux.py", line 21, in <module>
    from . import mmr_auxe, resources
ImportError: cannot import name 'mmr_auxe' from partially initialized module 'niftypet.nipet' (most likely due to a circular import) (/venv/NIPET/niftypet/nipet/__init__.py)
```

I have also tried to install nipet via niftypet and directly via pip but the error still occurs. Any feedback or suggestions are appreciated!
Best, Melissa
[Dockerfile.txt](https://github.com/NiftyPET/NiftyPET/files/12313853/Dockerfile.txt)

**Comment by casperdcl** [comment]
- [x] NIMPA: fix silly build error https://github.com/NiftyPET/NIMPA/pull/30
- [x] NIMPA: support docker build https://github.com/NiftyPET/NIMPA/pull/31
- [ ] NIPET: support docker build

☝️ @pjmark you might have to tackle the last bullet point as I don't have much time :)
